"""add initiative_bonus to characters

Revision ID: 515254ab6d50
Revises: ccdde42289b4
Create Date: 2026-03-15 20:41:50.620687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "515254ab6d50"
down_revision: Union[str, Sequence[str], None] = "ccdde42289b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attacks", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "_character_attack_name_uc", ["character_id", "name"]
        )

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("initiative_bonus", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_column("initiative_bonus")

    with op.batch_alter_table("attacks", schema=None) as batch_op:
        batch_op.drop_constraint("_character_attack_name_uc", type_="unique")

    # ### end Alembic commands ###
