"""make core stats nullable

Revision ID: a85d17a1341e
Revises: 515254ab6d50
Create Date: 2026-03-15 21:37:18.531561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85d17a1341e'
down_revision: Union[str, Sequence[str], None] = '515254ab6d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dexterity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('constitution',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('intelligence',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wisdom',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('charisma',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('charisma',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wisdom',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('intelligence',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('constitution',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dexterity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('strength',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
