"""Update models to Mapped and use SkillProficiencyStatus

Revision ID: abeb56fc9606
Revises: a59f4e37528b
Create Date: 2026-03-13 17:22:11.848096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abeb56fc9606"
down_revision: Union[str, Sequence[str], None] = "a59f4e37528b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character_skills", schema=None) as batch_op:
        batch_op.alter_column(
            "proficiency", existing_type=sa.VARCHAR(length=18), nullable=False
        )

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("strength", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("dexterity", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "constitution", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "intelligence", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("wisdom", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("charisma", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "st_prof_strength", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "st_prof_dexterity", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "st_prof_constitution", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "st_prof_intelligence", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "st_prof_wisdom", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "st_prof_charisma", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column(
            "st_prof_charisma", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "st_prof_wisdom", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "st_prof_intelligence", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "st_prof_constitution", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "st_prof_dexterity", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "st_prof_strength", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("charisma", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("wisdom", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("intelligence", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("constitution", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("dexterity", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("strength", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("character_skills", schema=None) as batch_op:
        batch_op.alter_column(
            "proficiency", existing_type=sa.VARCHAR(length=18), nullable=True
        )

    # ### end Alembic commands ###
