"""Allow multiple characters per user server

Revision ID: b3b3ef3ceed8
Revises: 1387e1e31515
Create Date: 2026-03-13 17:55:58.487483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3b3ef3ceed8"
down_revision: Union[str, Sequence[str], None] = "1387e1e31515"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Handle constraints and ensure is_active is NOT NULL
    # is_active column already exists from a failed attempt
    op.execute("UPDATE characters SET is_active = 1 WHERE is_active IS NULL")

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("is_active", nullable=False)
        # Drop the old constraint
        # Need to be careful with names as Alembic uses naming conventions
        batch_op.drop_constraint("_user_server_uc", type_="unique")
        # Add the new constraint
        batch_op.create_unique_constraint(
            "_user_server_name_uc", ["user_id", "server_id", "name"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_constraint("_user_server_name_uc", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("_user_server_uc"), ["user_id", "server_id"]
        )
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
