"""Add party models

Revision ID: ccdde42289b4
Revises: b3b3ef3ceed8
Create Date: 2026-03-13 18:16:38.628759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccdde42289b4"
down_revision: Union[str, Sequence[str], None] = "b3b3ef3ceed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gm_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gm_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "name", name="_server_party_name_uc"),
    )
    op.create_table(
        "party_character",
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.id"],
        ),
    )
    with op.batch_alter_table("user_server", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active_party_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_user_server_active_party", "parties", ["active_party_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_server", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_server_active_party", type_="foreignkey")
        batch_op.drop_column("active_party_id")

    op.drop_table("party_character")
    op.drop_table("parties")
    # ### end Alembic commands ###
