"""add weapon metadata fields to attack

Revision ID: dc2151d497c1
Revises: 775c1697e29e
Create Date: 2026-03-18 14:37:34.560308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc2151d497c1"
down_revision: Union[str, Sequence[str], None] = "775c1697e29e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attacks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("damage_type", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("weapon_category", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("range_normal", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("range_long", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("two_handed_damage", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("properties_json", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("is_imported", sa.Boolean(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("encounter_turns", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "characters", ["character_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("encounter_turns", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "characters", ["character_id"], ["id"])

    with op.batch_alter_table("attacks", schema=None) as batch_op:
        batch_op.drop_column("is_imported")
        batch_op.drop_column("properties_json")
        batch_op.drop_column("two_handed_damage")
        batch_op.drop_column("range_long")
        batch_op.drop_column("range_normal")
        batch_op.drop_column("weapon_category")
        batch_op.drop_column("damage_type")

    # ### end Alembic commands ###
